name: Create Milestone

on:
  issues:
    types: [opened,labeled]

jobs:
  create_milestone:
    runs-on: ubuntu-latest

    steps:
    - name: Check if issue has milestone label
      id: check_label
      uses: actions/github-script@v6
      with:
        script: |
          const label = context.payload.issue.labels.find(label => label.name === 'milestone');
          return label ? 'true' : 'false';
    - name: show label
      run: echo ${{ steps.check_label.outputs.result }}